# Generated by Django 4.2.4 on 2023-09-25 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('protected_areas', models.CharField(blank=True, max_length=255, null=True)),
                ('seasonal_restrictions', models.TextField(blank=True, null=True)),
                ('required_permits', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('water_quality', models.CharField(blank=True, max_length=255, null=True)),
                ('currents', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spot_type', models.CharField(choices=[('beach', 'Beach'), ('lake', 'Lakes'), ('river', 'Rivers'), ('waterfall', 'Waterfalls'), ('pool', 'Pools'), ('cave', 'Caves')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('images', models.ImageField(blank=True, null=True, upload_to='spots/')),
                ('regulations', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.regulation')),
                ('safety_information', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.safetyinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
